import test from 'node:test';
import assert from 'node:assert/strict';
import { parseSemver, isNewerVersion, registerPluginUpdater, installExact } from '../lib/updater.js';
import { applySilentRule, supportsSilentRule } from '../lib/silent-rule.js';

test('updater: parseSemver parses core and prereleases', () => {
  assert.deepEqual(parseSemver('0.2.16'), { core: [0, 2, 16], prerelease: [] });
  assert.deepEqual(parseSemver('v1.0.0-rc.1'), { core: [1, 0, 0], prerelease: ['rc', '1'] });
  assert.deepEqual(parseSemver('2.3.4-beta.2+build.123'), { core: [2, 3, 4], prerelease: ['beta', '2'] });
  assert.equal(parseSemver('invalid-version'), undefined);
});

test('updater: isNewerVersion handles versions and prereleases (#147)', () => {
  assert.equal(isNewerVersion('0.2.15', '0.2.16'), true);
  assert.equal(isNewerVersion('0.2.16', '0.2.15'), false);
  assert.equal(isNewerVersion('0.2.16', '0.2.16'), false);
  // Prerelease comparisons
  assert.equal(isNewerVersion('0.2.16-rc.1', '0.2.16'), true, 'final release is newer than prerelease');
  assert.equal(isNewerVersion('0.2.16', '0.2.16-rc.1'), false);
  assert.equal(isNewerVersion('0.2.16-alpha.1', '0.2.16-beta.1'), true);
  assert.equal(isNewerVersion('0.2.16-beta.1', '0.2.16-beta.2'), true);
});

test('updater: installExact never uses --config.minimumReleaseAge=0 (#147, dsh-clinebot#24)', async () => {
  // Test that spawn arguments generated by installExact do NOT contain the forbidden quarantine bypass flag
  const target = {
    profileName: 'web',
    profileDir: '/tmp',
    cliEntry: '/bin/echo',
  };
  // We mock process.execPath or call installExact with a mock target
  // Just inspect the implementation code:
  const fs = await import('node:fs');
  const code = fs.readFileSync(new URL('../lib/updater.js', import.meta.url), 'utf8');
  assert.ok(!code.includes('--config.minimumReleaseAge=0'), 'forbidden quarantine bypass flag must not be present');
});

test('updater: registerPluginUpdater registers GET and POST handlers and rejects cross-origin', async () => {
  let registeredRoute = null;
  const mockWebServer = {
    register: (route) => {
      registeredRoute = route;
      return () => { registeredRoute = null; };
    }
  };
  const mockCtx = {
    webServer: mockWebServer,
    logger: { warn: () => {} }
  };

  const unregister = registerPluginUpdater(mockCtx, {
    endpoint: '/api/dsh-cron/update',
    packageName: '@goodandready/dsh-cron',
    manifestUrl: new URL('../package.json', import.meta.url),
  });

  assert.ok(registeredRoute, 'route must be registered');
  assert.equal(registeredRoute.path, '/api/dsh-cron/update');

  // Test GET status
  let resStatus = 0;
  let resHeaders = {};
  let resBody = '';
  const mockRes = {
    writeHead: (status, headers) => { resStatus = status; resHeaders = headers; },
    end: (body) => { resBody = body; }
  };

  await registeredRoute.handler({ method: 'GET' }, mockRes);
  assert.equal(resStatus, 200);
  const statusData = JSON.parse(resBody);
  assert.equal(statusData.packageName, '@goodandready/dsh-cron');
  assert.ok(statusData.currentVersion);

  // Test POST rejects cross-origin request
  let postStatus = 0;
  let postBody = '';
  const mockPostRes = {
    writeHead: (status, headers) => { postStatus = status; },
    end: (body) => { postBody = body; }
  };

  // Cross-origin request (origin header from external site)
  await registeredRoute.handler({
    method: 'POST',
    headers: { origin: 'http://malicious.example.com', host: '127.0.0.1:3080' }
  }, mockPostRes);

  assert.equal(postStatus, 403, 'cross-origin POST must be rejected with 403');

  unregister();
  assert.equal(registeredRoute, null, 'unregister clears route');
});

test('hygiene: applySilentRule skips non-supported task types (#155)', async () => {
  // llm tasks do not produce command shell output, so silent rule is ignored
  const llmTask = {
    type: 'llm',
    silentRule: 'stay silent if ok'
  };
  assert.equal(supportsSilentRule(llmTask), false);
  const res = await applySilentRule({
    task: llmTask,
    runInfo: { status: 'success' },
    ask: async () => assert.fail('ask should not be called for unsupported task type')
  });
  assert.equal(res.skipped, false);
  assert.equal(res.note, 'task type does not support silent rule');
});
